/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CliLoginRouteImport } from './routes/cli-login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as SharedWithMeRouteImport } from './routes/shared-with-me'
import { Route as WorktreesRouteImport } from './routes/worktrees'
import { Route as NodesNodeIdRouteImport } from './routes/nodes.$nodeId'
import { Route as SpacesSpaceIdRouteImport } from './routes/spaces.$spaceId'
import { Route as SpacesSpaceIdMembersRouteImport } from './routes/spaces_.$spaceId.members'
import { Route as SpacesSpaceIdTrashRouteImport } from './routes/spaces_.$spaceId.trash'
import { Route as WorktreesWorktreeIdUnitsUnitIdModeRouteImport } from './routes/worktrees_.$worktreeId_.units.$unitId.$mode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CliLoginRoute = CliLoginRouteImport.update({
  id: '/cli-login',
  path: '/cli-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedWithMeRoute = SharedWithMeRouteImport.update({
  id: '/shared-with-me',
  path: '/shared-with-me',
  getParentRoute: () => rootRouteImport,
} as any)
const WorktreesRoute = WorktreesRouteImport.update({
  id: '/worktrees',
  path: '/worktrees',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesNodeIdRoute = NodesNodeIdRouteImport.update({
  id: '/nodes/$nodeId',
  path: '/nodes/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSpaceIdRoute = SpacesSpaceIdRouteImport.update({
  id: '/spaces/$spaceId',
  path: '/spaces/$spaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSpaceIdMembersRoute = SpacesSpaceIdMembersRouteImport.update({
  id: '/spaces_/$spaceId/members',
  path: '/spaces/$spaceId/members',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSpaceIdTrashRoute = SpacesSpaceIdTrashRouteImport.update({
  id: '/spaces_/$spaceId/trash',
  path: '/spaces/$spaceId/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const WorktreesWorktreeIdUnitsUnitIdModeRoute =
  WorktreesWorktreeIdUnitsUnitIdModeRouteImport.update({
    id: '/worktrees_/$worktreeId_/units/$unitId/$mode',
    path: '/worktrees/$worktreeId/units/$unitId/$mode',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cli-login': typeof CliLoginRoute
  '/demo': typeof DemoRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/recent': typeof RecentRoute
  '/shared-with-me': typeof SharedWithMeRoute
  '/worktrees': typeof WorktreesRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRoute
  '/spaces/$spaceId/members': typeof SpacesSpaceIdMembersRoute
  '/spaces/$spaceId/trash': typeof SpacesSpaceIdTrashRoute
  '/worktrees/$worktreeId/units/$unitId/$mode': typeof WorktreesWorktreeIdUnitsUnitIdModeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cli-login': typeof CliLoginRoute
  '/demo': typeof DemoRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/recent': typeof RecentRoute
  '/shared-with-me': typeof SharedWithMeRoute
  '/worktrees': typeof WorktreesRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRoute
  '/spaces/$spaceId/members': typeof SpacesSpaceIdMembersRoute
  '/spaces/$spaceId/trash': typeof SpacesSpaceIdTrashRoute
  '/worktrees/$worktreeId/units/$unitId/$mode': typeof WorktreesWorktreeIdUnitsUnitIdModeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cli-login': typeof CliLoginRoute
  '/demo': typeof DemoRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/recent': typeof RecentRoute
  '/shared-with-me': typeof SharedWithMeRoute
  '/worktrees': typeof WorktreesRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRoute
  '/spaces_/$spaceId/members': typeof SpacesSpaceIdMembersRoute
  '/spaces_/$spaceId/trash': typeof SpacesSpaceIdTrashRoute
  '/worktrees_/$worktreeId_/units/$unitId/$mode': typeof WorktreesWorktreeIdUnitsUnitIdModeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cli-login'
    | '/demo'
    | '/home'
    | '/login'
    | '/recent'
    | '/shared-with-me'
    | '/worktrees'
    | '/nodes/$nodeId'
    | '/spaces/$spaceId'
    | '/spaces/$spaceId/members'
    | '/spaces/$spaceId/trash'
    | '/worktrees/$worktreeId/units/$unitId/$mode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cli-login'
    | '/demo'
    | '/home'
    | '/login'
    | '/recent'
    | '/shared-with-me'
    | '/worktrees'
    | '/nodes/$nodeId'
    | '/spaces/$spaceId'
    | '/spaces/$spaceId/members'
    | '/spaces/$spaceId/trash'
    | '/worktrees/$worktreeId/units/$unitId/$mode'
  id:
    | '__root__'
    | '/'
    | '/cli-login'
    | '/demo'
    | '/home'
    | '/login'
    | '/recent'
    | '/shared-with-me'
    | '/worktrees'
    | '/nodes/$nodeId'
    | '/spaces/$spaceId'
    | '/spaces_/$spaceId/members'
    | '/spaces_/$spaceId/trash'
    | '/worktrees_/$worktreeId_/units/$unitId/$mode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CliLoginRoute: typeof CliLoginRoute
  DemoRoute: typeof DemoRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  RecentRoute: typeof RecentRoute
  SharedWithMeRoute: typeof SharedWithMeRoute
  WorktreesRoute: typeof WorktreesRoute
  NodesNodeIdRoute: typeof NodesNodeIdRoute
  SpacesSpaceIdRoute: typeof SpacesSpaceIdRoute
  SpacesSpaceIdMembersRoute: typeof SpacesSpaceIdMembersRoute
  SpacesSpaceIdTrashRoute: typeof SpacesSpaceIdTrashRoute
  WorktreesWorktreeIdUnitsUnitIdModeRoute: typeof WorktreesWorktreeIdUnitsUnitIdModeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli-login': {
      id: '/cli-login'
      path: '/cli-login'
      fullPath: '/cli-login'
      preLoaderRoute: typeof CliLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-with-me': {
      id: '/shared-with-me'
      path: '/shared-with-me'
      fullPath: '/shared-with-me'
      preLoaderRoute: typeof SharedWithMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worktrees': {
      id: '/worktrees'
      path: '/worktrees'
      fullPath: '/worktrees'
      preLoaderRoute: typeof WorktreesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/$nodeId': {
      id: '/nodes/$nodeId'
      path: '/nodes/$nodeId'
      fullPath: '/nodes/$nodeId'
      preLoaderRoute: typeof NodesNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$spaceId': {
      id: '/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof SpacesSpaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces_/$spaceId/members': {
      id: '/spaces_/$spaceId/members'
      path: '/spaces/$spaceId/members'
      fullPath: '/spaces/$spaceId/members'
      preLoaderRoute: typeof SpacesSpaceIdMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces_/$spaceId/trash': {
      id: '/spaces_/$spaceId/trash'
      path: '/spaces/$spaceId/trash'
      fullPath: '/spaces/$spaceId/trash'
      preLoaderRoute: typeof SpacesSpaceIdTrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worktrees_/$worktreeId_/units/$unitId/$mode': {
      id: '/worktrees_/$worktreeId_/units/$unitId/$mode'
      path: '/worktrees/$worktreeId/units/$unitId/$mode'
      fullPath: '/worktrees/$worktreeId/units/$unitId/$mode'
      preLoaderRoute: typeof WorktreesWorktreeIdUnitsUnitIdModeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CliLoginRoute: CliLoginRoute,
  DemoRoute: DemoRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  RecentRoute: RecentRoute,
  SharedWithMeRoute: SharedWithMeRoute,
  WorktreesRoute: WorktreesRoute,
  NodesNodeIdRoute: NodesNodeIdRoute,
  SpacesSpaceIdRoute: SpacesSpaceIdRoute,
  SpacesSpaceIdMembersRoute: SpacesSpaceIdMembersRoute,
  SpacesSpaceIdTrashRoute: SpacesSpaceIdTrashRoute,
  WorktreesWorktreeIdUnitsUnitIdModeRoute:
    WorktreesWorktreeIdUnitsUnitIdModeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
